import {Localized} from '../../ui/Language';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import Image from 'next/image';
import {projects} from '../../content';
import {pageMetadata} from '../../site';
import {MediaSlot,BeforeAfter,CTA} from '../../ui/Site';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);return p?pageMetadata({title:p.title,description:p.brief,path:`/work/${slug}`}):{};}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)notFound();return <Localized>{<><section className="project-hero"><MediaSlot label={p.title} image={p.image} video={p.video}/></section><section className="section project-detail"><Link className="text-link" href="/work">← All work</Link><p className="eyebrow">{p.category} / {p.industry}</p><h1>{p.title}</h1><span className="arabic" lang="ar" dir="rtl">{p.arabic}</span><div className="project-body"><div><h2>The brief</h2><p>{p.brief}</p></div><div><h2>{(p.image||p.video)&&!p.illustrative?'What we made':'What we create'}</h2><ul>{p.made.map(item=><li key={item}>{item}</li>)}</ul></div></div>{p.caseStudy&&!p.illustrative&&<div className="case-study"><p className="eyebrow">CLIENT CASE STUDY</p><div className="case-client">{p.caseStudy.clientLogo&&<Image src={p.caseStudy.clientLogo} alt={p.caseStudy.client} width={140} height={56}/>}<strong>{p.caseStudy.client}</strong></div><div className="project-body"><div><h2>The challenge</h2><p>{p.caseStudy.challenge}</p></div><div><h2>Our approach</h2><p>{p.caseStudy.approach}</p></div></div>{p.caseStudy.results.length>0&&<div className="project-result"><h2>Results</h2><ul className="check-list">{p.caseStudy.results.map(r=><li key={r}>{r}</li>)}</ul></div>}{p.caseStudy.testimonial&&<blockquote className="testimonial"><p>“{p.caseStudy.testimonial.quote}”</p><footer>{p.caseStudy.testimonial.name}, {p.caseStudy.testimonial.role}</footer></blockquote>}</div>}{p.illustrative&&<p className="asset-note">This is an illustrative concept for this service. It is not a completed client project.</p>}{p.before&&p.after&&<BeforeAfter before={p.before} after={p.after}/>} {p.approvedResult&&<div className="project-result"><h2>The result</h2><p>{p.approvedResult}</p></div>}<CTA topic={p.title}/></section></>}</Localized>;}
