import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import {services,projects,media} from './content';
import {serviceImage} from './visuals';
import {CTA,MediaSlot,ProjectCard,QualityBand,Industries,Steps,HealthBand} from './ui/Site';
export default function Home(){return <>
<section className="hero"><MediaSlot label="Creative production studio" shape="hero-media" image={media.heroImage} video={media.heroVideo}/><div className="hero-copy"><p className="eyebrow">DOHA, QATAR <span lang="ar" dir="rtl">الدوحة، قطر</span></p><h1>Digital ideas.<br/><em>Real results.</em></h1><p className="positioning">A Doha team with its own production studio.</p><p>Arabic and English. From the first idea to the final frame.</p><div className="hero-actions"><CTA/><CTA kind="check" className="outline"/></div></div><Link className="hero-work-link" href="/work">See our work <ArrowUpRight size={22}/></Link></section>
<section className="section"><div className="section-heading"><div><p className="eyebrow">OUR WORK / أعمالنا</p><h2>Let the work <em>speak.</em></h2></div><Link className="text-link" href="/work">Explore all work <ArrowUpRight size={19}/></Link></div><p className="asset-note">Explore our services through illustrative concepts. Client-approved case studies will be added next.</p><div className="projects">{projects.map(p=><ProjectCard key={p.slug} project={p}/>)}</div></section>
<section className="section services-home"><div className="section-heading"><div><p className="eyebrow">WHAT WE DO / خدماتنا</p><h2>Your next move,<br/><em>made here.</em></h2></div><Link className="text-link" href="/services">Our services <ArrowUpRight size={19}/></Link></div><div className="service-home-grid">{services.map(s=><Link className="service-home-card" href={`/services#${s.id}`} key={s.id}><MediaSlot label={s.title} image={serviceImage(s.id)}/><div><h3>{s.title}<ArrowUpRight size={19}/></h3><span className="arabic" lang="ar" dir="rtl">{s.arabic}</span><p>{s.intro}</p></div></Link>)}</div></section>
<QualityBand/><Industries/><section className="section process-home"><div className="section-heading"><div><p className="eyebrow">HOW WE WORK / كيف نعمل</p><h2>Clear steps.<br/><em>Better work.</em></h2></div><Link className="text-link" href="/how-we-work">Meet the process <ArrowUpRight size={19}/></Link></div><Steps/></section><HealthBand/></>;}
