'use client';

import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, X, Menu, Globe2, PenTool, BarChart3, Clapperboard, Sparkles, Check, Plus, Minus } from 'lucide-react';

const services = [
  { title: 'Brand & creative', icon: PenTool, text: 'A distinct identity. A lasting impression.', detail: 'From positioning and visual identity to campaign design, we create a consistent brand language that makes every touchpoint feel unmistakably yours.', items: ['Brand strategy & identity', 'Graphic & campaign design', 'Brand guidelines'] },
  { title: 'Digital marketing', icon: BarChart3, text: 'Reach the right people. Move them to act.', detail: 'We connect creative thinking with a clear marketing strategy, helping your business build meaningful relationships and turn attention into action.', items: ['Social media management', 'Paid search & social campaigns', 'Content strategy & SEO'] },
  { title: 'Web experiences', icon: Globe2, text: 'Beautiful to explore. Built to perform.', detail: 'We design and develop fast, accessible digital experiences that make your business easier to discover and your customers easier to serve.', items: ['Website design & development', 'E-commerce experiences', 'Website care & hosting'] },
  { title: 'Content & motion', icon: Clapperboard, text: 'Stories that stop the scroll.', detail: 'Bring your brand into focus with thoughtful photography, engaging video, and motion graphics designed for the channels your audience uses.', items: ['Photography & videography', 'Motion graphics', 'Social content production'] },
  { title: 'AI & automation', icon: Sparkles, text: 'Smarter systems. More possibilities.', detail: 'Make room for your next big idea with practical automation and intelligent experiences that simplify everyday business processes.', items: ['AI assistants', 'Workflow automation', 'Customer experience tools'] },
];
const projects = [
  { name: 'FORM / SPACE', type: 'Brand identity', className: 'form-project', description: 'A conceptual identity for a contemporary architecture studio. Precise typography and spatial compositions give the brand a confident, considered presence.' },
  { name: 'NOVA', type: 'Digital experience', className: 'nova-project', description: 'An e-commerce concept for a new generation of audio. A bold visual language pairs product storytelling with a simple, focused shopping experience.' },
  { name: 'botanica', type: 'Packaging & art direction', className: 'botanica-project', description: 'A packaging concept inspired by everyday rituals and natural ingredients. Soft colors, expressive type, and restrained design bring a sense of calm to the shelf.' },
];

function DigitalGlobe() {
  const dots = Array.from({ length: 480 }, (_, i) => {
    const phi = Math.acos(1 - 2 * (i + .5) / 480);
    const theta = Math.PI * (1 + Math.sqrt(5)) * i;
    const x = Math.sin(phi) * Math.cos(theta), y = Math.cos(phi), z = Math.sin(phi) * Math.sin(theta);
    return { x: 280 + x * 222, y: 270 + y * 222, r: 2 + (z + 1) * 3.5, opacity: .16 + (z + 1) * .39, z };
  }).sort((a, b) => a.z - b.z);
  return <svg className="globe-art" viewBox="0 0 560 550" aria-hidden="true"><defs><linearGradient id="blue" x1="0" x2="1" y2="1"><stop stopColor="#62e4ff"/><stop offset=".5" stopColor="#2b8eff"/><stop offset="1" stopColor="#3757e3"/></linearGradient><radialGradient id="halo"><stop stopColor="#126bf4" stopOpacity=".21"/><stop offset="1" stopColor="#126bf4" stopOpacity="0"/></radialGradient></defs><circle cx="280" cy="270" r="260" fill="url(#halo)"/><g transform="rotate(-23 280 270)">{dots.map((dot, i) => <circle key={i} cx={dot.x} cy={dot.y} r={dot.r} fill="url(#blue)" opacity={dot.opacity}/>)}</g><g fill="#61bbff"><rect x="475" y="107" width="16" height="16"/><rect x="509" y="75" width="23" height="23"/><rect x="492" y="153" width="10" height="10"/><rect x="455" y="64" width="8" height="8"/></g></svg>;
}

export default function Agency() {
  const [menu, setMenu] = useState(false);
  const [modal, setModal] = useState<'contact' | number | null>(null);
  const [project, setProject] = useState<number | null>(null);
  const [expanded, setExpanded] = useState<number | null>(0);
  const [submitted, setSubmitted] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  const isOpen = modal !== null || project !== null;
  useEffect(() => {
    if (isOpen) { dialog.current?.showModal(); document.body.style.overflow = 'hidden'; }
    else { dialog.current?.close(); document.body.style.overflow = ''; }
    return () => { document.body.style.overflow = ''; };
  }, [isOpen]);
  function close() { setModal(null); setProject(null); setSubmitted(false); }
  function contact() { setProject(null); setModal('contact'); setMenu(false); setSubmitted(false); }
  return <>
    <a href="#main" className="skip-link">Skip to content</a>
    <header className="header"><a href="#" className="brand" aria-label="ALQA home"><Image src="/brand/logo.png" alt="ALQA" width={1302} height={867} priority/><span>Digital Ideas.<br/>Real Results.</span></a><nav aria-label="Main navigation" className={menu ? 'nav open' : 'nav'}>{[['About', '#about'], ['Services', '#services'], ['Our work', '#work'], ['Our approach', '#approach']].map(([label, href]) => <a key={href} href={href} onClick={() => setMenu(false)}>{label}</a>)}</nav><button className="button header-cta" onClick={contact}>Let’s talk <ArrowUpRight size={17}/></button><button className="menu-toggle" aria-label={menu ? 'Close menu' : 'Open menu'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></header>
    <main id="main">
      <section className="hero"><div className="hero-grid"/><div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> YOUR NEXT CHAPTER STARTS HERE</p><h1>Digital ideas.<br/>Real <span className="serif">results.</span><span className="blue-period">↗</span></h1><p className="hero-description">We turn ambitious ideas into brands,<br className="desktop-break"/> experiences, and digital growth that matter.</p><div className="hero-actions"><button className="button blue" onClick={contact}>Let’s build something <ArrowUpRight size={19}/></button><a className="text-link" href="#work">Explore our work <ArrowRight size={18}/></a></div><div className="hero-note"><span className="tiny-cross">✳</span><p>Creative thinking.<br/><strong>Measurable impact.</strong></p></div></div><div className="hero-visual"><div className="orbit-caption"><span className="status-dot"/> CONNECTING IDEAS TO POSSIBILITIES</div><DigitalGlobe/><span className="visual-tag tag-top">A little imagination.</span><span className="visual-tag tag-bottom">A world of potential. <ArrowUpRight size={16}/></span><div className="coordinate">CREATIVE MINDS. DIGITAL POSSIBILITIES.<br/>THINKING BEYOND BOUNDARIES</div></div><div className="hero-bottom"><span>STRATEGY. CREATIVITY. TECHNOLOGY.</span><a href="#about">SCROLL TO DISCOVER <ArrowDown size={15}/></a></div></section>
      <div className="capabilities-strip"><span>Ideas with purpose.</span><span className="strip-star">✳</span><span>Design with distinction.</span><span className="strip-star">✳</span><span>Growth with direction.</span><span className="strip-star">✳</span><span>That’s ALQA.</span></div>
      <section id="about" className="section about"><div><p className="eyebrow dark"><span className="small-line"/> THE THINKING BEHIND THE DOING</p><h2>Your ambition.<br/>Our <span className="serif blue-text">creative energy.</span></h2></div><div className="about-text"><p>Great things happen when the right ideas meet the right people.</p><p>We’re a creative and digital partner for businesses ready to move forward. Bringing strategy, design, and technology together, we help you build a brand people remember — and a business that keeps growing.</p><a href="#approach" className="text-link dark-link">Get to know our approach <ArrowUpRight size={19}/></a></div></section>
      <section id="services" className="section services"><div className="section-heading"><div><p className="eyebrow dark"><span className="small-line"/> WHAT WE DO</p><h2>Made for your<br/><span className="serif">next big move.</span></h2></div><p>One creative partner.<br/>A whole world of possibilities.</p></div><div className="services-grid">{services.map((s, i) => <button className="service-card" key={s.title} onClick={() => setModal(i)}><div className="service-card-top"><s.icon size={29} strokeWidth={1.4}/><span>0{i + 1}</span></div><h3>{s.title}</h3><p>{s.text}</p><span className="service-link">Discover more <ArrowUpRight size={20}/></span></button>)}</div></section>
      <section id="work" className="section work"><div className="section-heading"><div><p className="eyebrow dark"><span className="small-line"/> A GLIMPSE OF WHAT’S POSSIBLE</p><h2>Ideas, <span className="serif">in the wild.</span></h2></div><span className="concept-label">SELECTED DESIGN CONCEPTS</span></div><div className="projects">{projects.map((p, i) => <button className="project-card" key={p.name} onClick={() => setProject(i)}><div className={`project-art ${p.className}`}><span className="project-open"><ArrowUpRight size={23}/></span>{i === 0 ? <><span className="form-small">ARCHITECTURE<br/>WITH INTENTION.</span><div className="architecture"><div/><div/><div/></div><span className="form-name">FORM<span>/</span>SPACE</span></> : i === 1 ? <><span className="nova-small">SOUND. REIMAGINED.</span><div className="headphones"><div className="headband"/><div className="ear left"/><div className="ear right"/></div><span className="nova-name">NOVA<span>®</span></span></> : <><span className="botanica-small">A LITTLE CLOSER TO NATURE.</span><div className="bottle"><div className="bottle-cap"/><span>botanica</span><small>DAILY BALANCE<br/>BOTANICAL CARE</small></div><div className="leaf leaf-one"/><div className="leaf leaf-two"/><span className="botanica-name">Naturally,<br/><em>beautiful.</em></span></>}</div><div className="project-caption"><h3>{p.name}</h3><span>{p.type}</span></div></button>)}</div><p className="work-note">An exploration of our creative direction. Concept projects shown for illustration.</p></section>
      <section id="approach" className="section approach"><div><p className="eyebrow"><span className="small-line"/> HOW WE MAKE IT HAPPEN</p><h2>Good chemistry.<br/><span className="serif">Great outcomes.</span></h2><p className="approach-intro">A shared vision. An open conversation.<br/>A process that keeps moving you forward.</p><button className="button blue" onClick={contact}>Find your next step <ArrowUpRight size={19}/></button></div><div className="steps">{[{title:'Discover & align',text:'We listen first. Together, we define your goals, understand your audience, and find the opportunity that makes your brand different.'},{title:'Imagine & create',text:'Strategy becomes a creative direction. We explore, design, and refine with you to build something that feels right and works hard.'},{title:'Launch & evolve',text:'We bring the idea to life, learn from its performance, and keep improving. Because the best results come from moving forward together.'}].map((step,i) => <div className="step" key={step.title}><button onClick={() => setExpanded(expanded === i ? null : i)} aria-expanded={expanded === i} aria-controls={`step-${i}`}><span className="step-number">0{i+1}</span><h3>{step.title}</h3>{expanded === i ? <Minus size={21}/> : <Plus size={21}/>}</button><div id={`step-${i}`} hidden={expanded !== i}><p>{step.text}</p></div></div>)}</div></section>
      <section className="section contact-section"><p className="eyebrow dark"><span className="status-dot"/> GOOD IDEAS START WITH A CONVERSATION</p><div className="contact-heading"><h2>Have something<br/>in <span className="serif blue-text">mind?</span></h2><button className="round-cta" onClick={contact} aria-label="Start a project"><ArrowUpRight size={47}/></button></div><p>Let’s turn “what if” into what’s next.</p></section>
    </main>
    <footer className="footer"><div className="footer-top"><a className="brand footer-brand" href="#"><Image src="/brand/logo.png" alt="ALQA" width={1302} height={867}/><Image className="tagline-image" src="/brand/tag.png" alt="Digital Ideas. Real Results." width={1314} height={141}/></a><div><span className="footer-label">EXPLORE</span><a href="#about">About ALQA</a><a href="#services">Our services</a><a href="#work">Our work</a></div><div><span className="footer-label">LET’S CONNECT</span><button onClick={contact}>Start a conversation <ArrowUpRight size={15}/></button><a href="#approach">Our approach</a><span className="footer-motto">Big ideas welcome.</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} ALQA. All rights reserved.</span><span>CREATIVE MINDS. CONNECTED POSSIBILITIES. <span className="blue-text">↗</span></span><a href="#">Back to top ↑</a></div></footer>
    <dialog ref={dialog} aria-label="ALQA project and service information" className="dialog" onCancel={close} onClick={e => { if(e.target === dialog.current) close(); }}><button className="dialog-close" onClick={close} aria-label="Close dialog"><X size={23}/></button>{modal === 'contact' ? <><p className="eyebrow dark">LET’S CREATE WHAT’S NEXT</p><h2>Tell us your <span className="serif blue-text">idea.</span></h2>{submitted ? <div className="success"><Check size={34}/><h3>Your project brief is ready.</h3><p>We’ve downloaded your brief so you can keep it and share it with the ALQA team. Online enquiry delivery will be available once the business contact details are configured.</p><button className="button blue" onClick={close}>Done <ArrowRight size={18}/></button></div> : <form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const content = `ALQA PROJECT ENQUIRY\n\nName: ${data.get('name')}\nEmail: ${data.get('email')}\nService: ${data.get('service')}\n\nProject idea:\n${data.get('message')}`; const url = URL.createObjectURL(new Blob([content], {type:'text/plain'})); const a = document.createElement('a'); a.href = url; a.download = 'ALQA-project-brief.txt'; a.click(); URL.revokeObjectURL(url); setSubmitted(true); }}><div className="form-row"><label>Your name<input name="name" required autoComplete="name" placeholder="How should we call you?" maxLength={120}/></label><label>Email address<input name="email" type="email" required autoComplete="email" placeholder="you@company.com" maxLength={200}/></label></div><label>What can we help with?<select name="service" defaultValue="Not sure yet"><option>Not sure yet</option>{services.map(s => <option key={s.title}>{s.title}</option>)}</select></label><label>A little about your project<textarea name="message" required rows={4} placeholder="The idea, the ambition, the challenge…" maxLength={5000}/></label><p className="form-note">Create a downloadable brief to share with our team. This preview does not send your details online.</p><button type="submit" className="button blue">Create project brief <ArrowUpRight size={19}/></button></form>}</> : typeof modal === 'number' ? <><p className="eyebrow dark">WHAT WE DO / 0{modal + 1}</p><h2>{services[modal].title}</h2><p className="modal-description">{services[modal].detail}</p><ul className="detail-list">{services[modal].items.map(item => <li key={item}><Check size={18}/>{item}</li>)}</ul><button className="button blue" onClick={contact}>Let’s talk about it <ArrowUpRight size={18}/></button></> : project !== null ? <><p className="eyebrow dark">DESIGN CONCEPT / {projects[project].type}</p><h2>{projects[project].name}</h2><p className="modal-description">{projects[project].description}</p><p className="form-note">This is a studio concept, not a commissioned client case study.</p><button className="button blue" onClick={contact}>Create something like this <ArrowUpRight size={18}/></button></> : null}</dialog>
  </>;
}


