'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useState} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowUpRight, Menu, X, MessageCircle, Camera, Languages, CheckCheck, Utensils, HeartPulse, Building2, House, ShoppingBag, ImageIcon} from 'lucide-react';
import {industries, steps, whatsappHref, type Project} from '../content';
import {Localized,LanguageSelector} from './Language';
import {labelImage} from '../visuals';
export function CTA({kind='proposal',topic='',label,className=''}:{kind?:'check'|'proposal';topic?:string;label?:string;className?:string}) {return <Localized>{<a className={`button ${className}`} href={whatsappHref(kind,topic)}><MessageCircle size={17}/>{label ?? (kind==='check'?'Get a free Digital Health Check':'Request a proposal')}<ArrowUpRight size={17}/></a>}</Localized>;}
export function Header(){const [open,setOpen]=useState(false);const pathname=usePathname();return <Localized>{<><a href="#main" className="skip-link">Skip to content</a><header className="header"><Link href="/" className="brand" aria-label="ALQA home"><Image src="/brand/logo.png" alt="ALQA" width={1302} height={867} priority/><span>Digital Ideas.<br/>Real Results.</span></Link><nav aria-label="Main navigation" className={open?'nav open':'nav'}>{[['Home','/'],['Our Work','/work'],['Services','/services'],['How We Work','/how-we-work'],['Contact','/contact']].map(([name,url])=><Link aria-current={pathname===url?'page':undefined} href={url} key={url} onClick={()=>setOpen(false)}>{name}</Link>)}</nav><LanguageSelector/><CTA className="header-cta" label="Let’s talk"/><button className="menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header></>}</Localized>;}
export function Footer(){return <Localized>{<footer className="footer"><div className="footer-top"><div><Link href="/" className="brand footer-brand"><Image src="/brand/logo.png" alt="ALQA" width={1302} height={867}/></Link><p>A Doha team with its own production studio.</p><span lang="ar" dir="rtl" className="arabic">أفكار رقمية. نتائج حقيقية.</span></div><div><span className="eyebrow">EXPLORE</span><Link href="/work">Our Work</Link><Link href="/services">Services</Link><Link href="/how-we-work">How We Work</Link></div><div><span className="eyebrow">LET’S CONNECT</span><Link href="/contact">Contact our Doha team</Link><a href={whatsappHref()}>Request a proposal ↗</a><a href={whatsappHref('check')}>Free Digital Health Check ↗</a></div></div><div className="footer-bottom"><span>© 2026 ALQA. All rights reserved.</span><span>Digital Ideas. Real Results.</span><a href="#main">Back to top ↑</a></div></footer>}</Localized>;}
export function MediaSlot({label,shape='',image,video}:{label:string;shape?:string;image?:string;video?:string}){
 const source = image || labelImage(label);
 return <Localized>{<div className={`media-slot ${shape}`}>
 {video ? <video autoPlay muted loop playsInline controls preload="metadata" aria-label={label} src={video}/> : <Image src={source} alt={`${label} — illustrative concept visual`} fill sizes="(max-width: 760px) 100vw, 50vw" priority={shape==='hero-media'}/>}
 {!video && <span className="illustration-badge">Illustrative visual</span>}
 </div>}</Localized>;
}
export function ProjectCard({project}:{project:Project}){return <Localized>{<Link className="project-card" href={`/work/${project.slug}`}><MediaSlot label={project.title} image={project.image} video={project.video}/><div className="project-caption"><div><h3>{project.title}</h3><span className="arabic" lang="ar" dir="rtl">{project.arabic}</span></div><ArrowUpRight size={21}/></div><p className="project-category">{project.category} / {project.industry.split(',')[0]}</p></Link>}</Localized>;}
export function QualityBand(){return <Localized>{<section className="quality-band" aria-label="Our quality promise">{[{icon:Languages,title:'Native Arabic',text:'Every Arabic line written or checked by a native writer.'},{icon:Camera,title:'Shot in Qatar',text:'Our own local crew for commissioned shoots.'},{icon:CheckCheck,title:'Reviewed before you see it',text:'Every piece passes our quality check first.'},{icon:MessageCircle,title:'Fast replies',text:'A real person on WhatsApp. A team you can meet in Doha.'}].map(item=><div key={item.title}><item.icon size={24} strokeWidth={1.4}/><h3>{item.title}</h3><p>{item.text}</p></div>)}</section>}</Localized>;}
export function HealthBand(){return <Localized>{<section className="health-band"><div><p className="eyebrow">A FRESH LOOK AT YOUR DIGITAL PRESENCE</p><h2>Three fixes.<br/><em>A clearer next step.</em></h2><p>We review your Instagram, Google Business profile and website, and send you a short video with 3 fixes. Free, no obligation.</p></div><CTA kind="check" label="Get my free check" className="light"/></section>}</Localized>;}
export function Steps(){return <Localized>{<div className="steps-grid">{steps.map((s,i)=><article key={s.title}><span className="step-number">0{i+1}</span><span className="arabic" lang="ar" dir="rtl">{s.arabic}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div>}</Localized>;}
export function Industries(){const icons=[Utensils,HeartPulse,Building2,House,ShoppingBag];return <Localized>{<section className="section industries"><p className="eyebrow">BUILT AROUND YOUR BUSINESS</p><h2>Local knowledge.<br/><em>Work that fits.</em></h2><div className="industry-grid">{industries.map((s,i)=>{const Icon=icons[i];return <article className={i<2?'industry focus':'industry'} key={s.title}><Icon size={29} strokeWidth={1.4}/><h3>{s.title}</h3><span lang="ar" dir="rtl" className="arabic">{s.arabic}</span><p>{s.text}</p><Link href={`/work?industry=${encodeURIComponent(s.title)}`}>Explore work <ArrowUpRight size={17}/></Link></article>;})}</div></section>}</Localized>;}
export function BeforeAfter({before,after}:{before:string;after:string}){const[value,setValue]=useState(50);return <Localized>{<div className="before-after"><div className="comparison-images"><Image src={before} alt="Before the project" fill sizes="100vw"/><div style={{clipPath:`inset(0 ${100-value}% 0 0)`}} className="comparison-after"><Image src={after} alt="After the project" fill sizes="100vw"/></div><div className="comparison-divider" style={{left:`${value}%`}}/><span>Before</span><span>After</span></div><label>Compare before and after<input type="range" min="0" max="100" value={value} onChange={e=>setValue(Number(e.target.value))}/></label></div>}</Localized>;}

